# Generated by Django 3.1.5 on 2021-04-25 10:53

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210414_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=network.models.default_start_time),
        ),
    ]
