# Generated by Django 3.1.5 on 2021-05-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='poster',
        ),
    ]
