# Generated by Django 3.1.5 on 2021-05-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210524_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='timestamp',
        ),
    ]
