# Generated by Django 3.1.5 on 2021-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210202_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='images/image-not-found.jpg', upload_to=''),
        ),
    ]
