# Generated by Django 3.1.5 on 2021-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='auctions/images/image-not-found.jpg', upload_to=''),
        ),
    ]
