# Generated by Django 3.1.5 on 2021-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.URLField(default='https://www.thermaxglobal.com/wp-content/uploads/2020/05/image-not-found.jpg'),
        ),
    ]
