# Generated by Django 3.1.5 on 2021-02-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210203_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Other', max_length=20),
            preserve_default=False,
        ),
    ]
