# Generated by Django 3.1.5 on 2021-02-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='newOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='newowner', to='auctions.user'),
            preserve_default=False,
        ),
    ]
