# Generated by Django 3.1.5 on 2021-02-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='watcher',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchee', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
